image: node:14

stages:
  - pre-build
  - test
  - build
  - deploy

install:
  stage: pre-build
  script:
    - npm install
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - install
  script:
    - npm run test

prettier:
  stage: test
  dependencies:
    - install
  script:
    - npm run prettier

lint:
  stage: test
  dependencies:
    - install
  script:
    - npm run lint

build:
  stage: build
  dependencies:
    - install
  script:
    - npm run build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success

deploy:
  stage: deploy
  dependencies:
    - install
    - build
  script:
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
