name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on contentful publish new post
  repository_dispatch:
    types: 

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      
      - name: Install dependecies
        run: |
          echo Installing things...
          yarn install --prefer-offline
          echo Instalation finished


          
