name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on contentful publish new post
  repository_dispatch:
    types: 

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=site --functions=functions
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

          
